[package]
name = "logger"
version = "0.1.0"
authors = ["NexiNov <nexinov@gud-o15.localdomain>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
